import { PokemonCard } from "@prisma/client";

export const pokemonCardsArr: PokemonCard[] = [
  {
    id: 1,
    name: "Bulbasaur",
    rarity: "common",
    image: "/1.jpg",
    sellValue: 1,
  },
  {
    id: 2,
    name: "Ivysaur",
    rarity: "common",
    image: "/2.jpg",
    sellValue: 1,
  },
  {
    id: 3,
    name: "Venusaur EX",
    rarity: "doubleRare",
    image: "/3.jpg",
    sellValue: 10,
  },
  {
    id: 4,
    name: "Charmander",
    rarity: "common",
    image: "/4.jpg",
    sellValue: 1,
  },
  {
    id: 5,
    name: "Charmeleon",
    rarity: "common",
    image: "/5.jpg",
    sellValue: 1,
  },
  {
    id: 6,
    name: "Charizard EX",
    rarity: "doubleRare",
    image: "/6.jpg",
    sellValue: 10,
  },
  {
    id: 7,
    name: "Squirtle",
    rarity: "common",
    image: "/7.jpg",
    sellValue: 1,
  },
  {
    id: 8,
    name: "Wartortle",
    rarity: "common",
    image: "/8.jpg",
    sellValue: 1,
  },
  {
    id: 9,
    name: "Blastoise EX",
    rarity: "doubleRare",
    image: "/9.jpg",
    sellValue: 10,
  },
  {
    id: 10,
    name: "Caterpie",
    rarity: "common",
    image: "/10.jpg",
    sellValue: 1,
  },
  {
    id: 11,
    name: "Metapod",
    rarity: "common",
    image: "/11.jpg",
    sellValue: 1,
  },
  {
    id: 12,
    name: "Butterfree",
    rarity: "uncommon",
    image: "/12.jpg",
    sellValue: 2,
  },
  {
    id: 13,
    name: "Weedle",
    rarity: "common",
    image: "/13.jpg",
    sellValue: 1,
  },
  {
    id: 14,
    name: "Kakuna",
    rarity: "common",
    image: "/14.jpg",
    sellValue: 1,
  },
  {
    id: 15,
    name: "Beedrill",
    rarity: "rare",
    image: "/14.jpg",
    sellValue: 5,
  },
  {
    id: 16,
    name: "Pidgey",
    rarity: "common",
    image: "/16.jpg",
    sellValue: 1,
  },
  {
    id: 17,
    name: "Pidgeotto",
    rarity: "common",
    image: "/17.jpg",
    sellValue: 1,
  },
  {
    id: 18,
    name: "Pidgeot",
    rarity: "uncommon",
    image: "/18.jpg",
    sellValue: 2,
  },
  {
    id: 19,
    name: "Rattata",
    rarity: "common",
    image: "/19.jpg",
    sellValue: 1,
  },
  {
    id: 20,
    name: "Raticate",
    rarity: "uncommon",
    image: "/20.jpg",
    sellValue: 2,
  },
  {
    id: 21,
    name: "Spearow",
    rarity: "common",
    image: "/21.jpg",
    sellValue: 1,
  },
  {
    id: 22,
    name: "Fearow",
    rarity: "uncommon",
    image: "/22.jpg",
    sellValue: 2,
  },
  {
    id: 23,
    name: "Ekans",
    rarity: "common",
    image: "/23.jpg",
    sellValue: 1,
  },
  {
    id: 24,
    name: "Arbok",
    rarity: "doubleRare",
    image: "/24.jpg",
    sellValue: 10,
  },
  {
    id: 25,
    name: "Pikachu",
    rarity: "common",
    image: "/25.jpg",
    sellValue: 1,
  },
  {
    id: 26,
    name: "Raichu",
    rarity: "rare",
    image: "/26.jpg",
    sellValue: 5,
  },
  {
    id: 27,
    name: "Sandschrew",
    rarity: "common",
    image: "/27.jpg",
    sellValue: 1,
  },
  {
    id: 28,
    name: "Sandslash",
    rarity: "uncommon",
    image: "/28.jpg",
    sellValue: 2,
  },
  {
    id: 29,
    name: "Nidoran F",
    rarity: "common",
    image: "/29.jpg",
    sellValue: 1,
  },
  {
    id: 30,
    name: "Nidorina",
    rarity: "uncommon",
    image: "/30.jpg",
    sellValue: 2,
  },
  {
    id: 31,
    name: "Nidoqueen",
    rarity: "uncommon",
    image: "/31.jpg",
    sellValue: 2,
  },
  {
    id: 32,
    name: "Nidoran M",
    rarity: "common",
    image: "/32.jpg",
    sellValue: 1,
  },
  {
    id: 33,
    name: "Nidorino",
    rarity: "uncommon",
    image: "/33.jpg",
    sellValue: 2,
  },
  {
    id: 34,
    name: "Nidoking",
    rarity: "rare",
    image: "/34.jpg",
    sellValue: 5,
  },
  {
    id: 35,
    name: "Clefairy",
    rarity: "common",
    image: "/35.jpg",
    sellValue: 1,
  },
  {
    id: 36,
    name: "Clefable",
    rarity: "uncommon",
    image: "/36.jpg",
    sellValue: 2,
  },
  {
    id: 37,
    name: "Vulpix",
    rarity: "common",
    image: "/37.jpg",
    sellValue: 1,
  },
  {
    id: 38,
    name: "Ninetails EX",
    rarity: "doubleRare",
    image: "/38.jpg",
    sellValue: 10,
  },
  {
    id: 39,
    name: "Jigglypuff",
    rarity: "common",
    image: "/39.jpg",
    sellValue: 1,
  },
  {
    id: 40,
    name: "Wigglytuff",
    rarity: "doubleRare",
    image: "/40.jpg",
    sellValue: 10,
  },
  {
    id: 41,
    name: "Zubat",
    rarity: "common",
    image: "/41.jpg",
    sellValue: 1,
  },
  {
    id: 42,
    name: "Golbat",
    rarity: "uncommon",
    image: "/42.jpg",
    sellValue: 2,
  },
  {
    id: 43,
    name: "Oddish",
    rarity: "common",
    image: "/43.jpg",
    sellValue: 1,
  },
  {
    id: 44,
    name: "Gloom",
    rarity: "uncommon",
    image: "/44.jpg",
    sellValue: 2,
  },
  {
    id: 45,
    name: "Vileplume",
    rarity: "rare",
    image: "/45.jpg",
    sellValue: 5,
  },
  {
    id: 46,
    name: "Paras",
    rarity: "common",
    image: "/46.jpg",
    sellValue: 1,
  },
  {
    id: 47,
    name: "Parasect",
    rarity: "uncommon",
    image: "/47.jpg",
    sellValue: 2,
  },
  {
    id: 48,
    name: "Venonat",
    rarity: "common",
    image: "/48.jpg",
    sellValue: 1,
  },
  {
    id: 49,
    name: "Venomoth",
    rarity: "uncommon",
    image: "/49.jpg",
    sellValue: 2,
  },
  {
    id: 50,
    name: "Diglett",
    rarity: "common",
    image: "/50.jpg",
    sellValue: 1,
  },
  {
    id: 51,
    name: "Dugtrio",
    rarity: "uncommon",
    image: "/51.jpg",
    sellValue: 2,
  },
  {
    id: 52,
    name: "Meowth",
    rarity: "common",
    image: "/52.jpg",
    sellValue: 1,
  },
  {
    id: 53,
    name: "Persian",
    rarity: "uncommon",
    image: "/53.jpg",
    sellValue: 2,
  },
  {
    id: 54,
    name: "Psyduck",
    rarity: "common",
    image: "/54.jpg",
    sellValue: 1,
  },
  {
    id: 55,
    name: "Golduck",
    rarity: "uncommon",
    image: "/55.jpg",
    sellValue: 2,
  },
  {
    id: 56,
    name: "Mankey",
    rarity: "common",
    image: "/56.jpg",
    sellValue: 1,
  },
  {
    id: 57,
    name: "Primeape",
    rarity: "uncommon",
    image: "/57.jpg",
    sellValue: 2,
  },
  {
    id: 58,
    name: "Growlithe",
    rarity: "common",
    image: "/58.jpg",
    sellValue: 1,
  },
  {
    id: 59,
    name: "Arcanine",
    rarity: "uncommon",
    image: "/59.jpg",
    sellValue: 2,
  },
  {
    id: 60,
    name: "Poliwag",
    rarity: "common",
    image: "/60.jpg",
    sellValue: 1,
  },
  {
    id: 61,
    name: "Poliwhirl",
    rarity: "common",
    image: "/61.jpg",
    sellValue: 1,
  },
  {
    id: 62,
    name: "Poliwrath",
    rarity: "uncommon",
    image: "/62.jpg",
    sellValue: 2,
  },
  {
    id: 63,
    name: "Abra",
    rarity: "common",
    image: "/63.jpg",
    sellValue: 1,
  },
  {
    id: 64,
    name: "Kadabra",
    rarity: "uncommon",
    image: "/64.jpg",
    sellValue: 2,
  },
  {
    id: 65,
    name: "Alakazam EX",
    rarity: "doubleRare",
    image: "/65.jpg",
    sellValue: 10,
  },
  {
    id: 66,
    name: "Machop",
    rarity: "common",
    image: "/66.jpg",
    sellValue: 1,
  },
  {
    id: 67,
    name: "Machoke",
    rarity: "uncommon",
    image: "/67.jpg",
    sellValue: 2,
  },
  {
    id: 68,
    name: "Machamp",
    rarity: "rare",
    image: "/68.jpg",
    sellValue: 5,
  },
  {
    id: 69,
    name: "Bellsprout",
    rarity: "common",
    image: "/69.jpg",
    sellValue: 1,
  },
  {
    id: 70,
    name: "Weepinbell",
    rarity: "common",
    image: "/70.jpg",
    sellValue: 1,
  },
  {
    id: 71,
    name: "Victreebel",
    rarity: "uncommon",
    image: "/71.jpg",
    sellValue: 2,
  },
  {
    id: 72,
    name: "Tentacool",
    rarity: "common",
    image: "/72.jpg",
    sellValue: 1,
  },
  {
    id: 73,
    name: "Tentacruel",
    rarity: "uncommon",
    image: "/73.jpg",
    sellValue: 2,
  },
  {
    id: 74,
    name: "Geodude",
    rarity: "common",
    image: "/74.jpg",
    sellValue: 1,
  },
  {
    id: 75,
    name: "Graveler",
    rarity: "uncommon",
    image: "/75.jpg",
    sellValue: 2,
  },
  {
    id: 76,
    name: "Golem EX",
    rarity: "doubleRare",
    image: "/76.jpg",
    sellValue: 10,
  },
  {
    id: 77,
    name: "Ponyta",
    rarity: "common",
    image: "/77.jpg",
    sellValue: 1,
  },
  {
    id: 78,
    name: "Rapidash",
    rarity: "uncommon",
    image: "/78.jpg",
    sellValue: 2,
  },
  {
    id: 79,
    name: "Slowpoke",
    rarity: "common",
    image: "/79.jpg",
    sellValue: 1,
  },
  {
    id: 80,
    name: "Slowbro",
    rarity: "uncommon",
    image: "/80.jpg",
    sellValue: 2,
  },
  {
    id: 81,
    name: "Magnemite",
    rarity: "common",
    image: "/81.jpg",
    sellValue: 1,
  },
  {
    id: 82,
    name: "Magneton",
    rarity: "uncommon",
    image: "/82.jpg",
    sellValue: 2,
  },
  {
    id: 83,
    name: "Farfetch'd",
    rarity: "common",
    image: "/83.jpg",
    sellValue: 1,
  },
  {
    id: 84,
    name: "Doduo",
    rarity: "common",
    image: "/84.jpg",
    sellValue: 1,
  },
  {
    id: 85,
    name: "Dodrio",
    rarity: "rare",
    image: "/85.jpg",
    sellValue: 5,
  },
  {
    id: 86,
    name: "Seel",
    rarity: "common",
    image: "/86.jpg",
    sellValue: 1,
  },
  {
    id: 87,
    name: "Dewgong",
    rarity: "uncommon",
    image: "/87.jpg",
    sellValue: 2,
  },
  {
    id: 88,
    name: "Grimer",
    rarity: "common",
    image: "/88.jpg",
    sellValue: 1,
  },
  {
    id: 89,
    name: "Muk",
    rarity: "uncommon",
    image: "/89.jpg",
    sellValue: 2,
  },
  {
    id: 90,
    name: "Shellder",
    rarity: "common",
    image: "/90.jpg",
    sellValue: 1,
  },
  {
    id: 91,
    name: "Cloyster",
    rarity: "uncommon",
    image: "/91.jpg",
    sellValue: 2,
  },
  {
    id: 92,
    name: "Gastly",
    rarity: "common",
    image: "/92.jpg",
    sellValue: 1,
  },
  {
    id: 93,
    name: "Haunter",
    rarity: "uncommon",
    image: "/93.jpg",
    sellValue: 2,
  },
  {
    id: 94,
    name: "Gengar",
    rarity: "rare",
    image: "/94.jpg",
    sellValue: 5,
  },
  {
    id: 95,
    name: "Onix",
    rarity: "uncommon",
    image: "/95.jpg",
    sellValue: 2,
  },
  {
    id: 96,
    name: "Drowsee",
    rarity: "common",
    image: "/96.jpg",
    sellValue: 1,
  },
  {
    id: 97,
    name: "Hypno",
    rarity: "uncommon",
    image: "/97.jpg",
    sellValue: 2,
  },
  {
    id: 98,
    name: "Krabby",
    rarity: "common",
    image: "/98.jpg",
    sellValue: 1,
  },
  {
    id: 99,
    name: "Kingler",
    rarity: "uncommon",
    image: "/99.jpg",
    sellValue: 2,
  },
  {
    id: 100,
    name: "Voltorb",
    rarity: "common",
    image: "/100.jpg",
    sellValue: 1,
  },
  {
    id: 101,
    name: "Elecrode",
    rarity: "rare",
    image: "/101.jpg",
    sellValue: 5,
  },
  {
    id: 102,
    name: "Exeggcute",
    rarity: "common",
    image: "/102.jpg",
    sellValue: 1,
  },
  {
    id: 103,
    name: "Exeggutor",
    rarity: "uncommon",
    image: "/103.jpg",
    sellValue: 2,
  },
  {
    id: 104,
    name: "Cubone",
    rarity: "common",
    image: "/104.jpg",
    sellValue: 1,
  },
  {
    id: 105,
    name: "Marowak",
    rarity: "rare",
    image: "/105.jpg",
    sellValue: 5,
  },
  {
    id: 106,
    name: "Hitmonlee",
    rarity: "uncommon",
    image: "/106.jpg",
    sellValue: 2,
  },
  {
    id: 107,
    name: "Hitmonchan",
    rarity: "uncommon",
    image: "/107.jpg",
    sellValue: 2,
  },
  {
    id: 108,
    name: "Lickitung",
    rarity: "common",
    image: "/108.jpg",
    sellValue: 1,
  },
  {
    id: 109,
    name: "Koffing",
    rarity: "common",
    image: "/109.jpg",
    sellValue: 1,
  },
  {
    id: 110,
    name: "Weezing",
    rarity: "rare",
    image: "/110.jpg",
    sellValue: 5,
  },
  {
    id: 111,
    name: "Ryhorn",
    rarity: "common",
    image: "/111.jpg",
    sellValue: 1,
  },
  {
    id: 112,
    name: "Rhydon",
    rarity: "uncommon",
    image: "/112.jpg",
    sellValue: 2,
  },
  {
    id: 113,
    name: "Chansey",
    rarity: "rare",
    image: "/113.jpg",
    sellValue: 5,
  },
  {
    id: 114,
    name: "Tangela",
    rarity: "common",
    image: "/114.jpg",
    sellValue: 2,
  },
  {
    id: 115,
    name: "Kangaskhan EX",
    rarity: "doubleRare",
    image: "/115.jpg",
    sellValue: 10,
  },
  {
    id: 116,
    name: "Horsey",
    rarity: "common",
    image: "/116.jpg",
    sellValue: 1,
  },
  {
    id: 117,
    name: "Seadra",
    rarity: "uncommon",
    image: "/117.jpg",
    sellValue: 2,
  },
  {
    id: 118,
    name: "Goldeen",
    rarity: "common",
    image: "/118.jpg",
    sellValue: 1,
  },
  {
    id: 119,
    name: "Seaking",
    rarity: "uncommon",
    image: "/119.jpg",
    sellValue: 2,
  },
  {
    id: 120,
    name: "Staryu",
    rarity: "common",
    image: "/120.jpg",
    sellValue: 1,
  },
  {
    id: 121,
    name: "Starmie",
    rarity: "rare",
    image: "/121.jpg",
    sellValue: 5,
  },
  {
    id: 122,
    name: "Mr. Mime",
    rarity: "rare",
    image: "/122.jpg",
    sellValue: 5,
  },
  {
    id: 123,
    name: "Scyther",
    rarity: "uncommon",
    image: "/123.jpg",
    sellValue: 2,
  },
  {
    id: 124,
    name: "Jynx EX",
    rarity: "doubleRare",
    image: "/124.jpg",
    sellValue: 10,
  },
  {
    id: 125,
    name: "Electabuzz",
    rarity: "common",
    image: "/125.jpg",
    sellValue: 1,
  },
  {
    id: 126,
    name: "Magmar",
    rarity: "common",
    image: "/126.jpg",
    sellValue: 1,
  },
  {
    id: 127,
    name: "Magmar",
    rarity: "uncommon",
    image: "/127.jpg",
    sellValue: 2,
  },
  {
    id: 128,
    name: "Tauros",
    rarity: "uncommon",
    image: "/128.jpg",
    sellValue: 2,
  },
  {
    id: 129,
    name: "Magikarp",
    rarity: "common",
    image: "/129.jpg",
    sellValue: 1,
  },
  {
    id: 130,
    name: "Gyarados",
    rarity: "rare",
    image: "/130.jpg",
    sellValue: 5,
  },
  {
    id: 131,
    name: "Lapras",
    rarity: "uncommon",
    image: "/131.jpg",
    sellValue: 2,
  },
  {
    id: 132,
    name: "Ditto",
    rarity: "rare",
    image: "/132.jpg",
    sellValue: 5,
  },
  {
    id: 133,
    name: "Eevee",
    rarity: "common",
    image: "/133.jpg",
    sellValue: 1,
  },
  {
    id: 134,
    name: "Vaporeon",
    rarity: "rare",
    image: "/134.jpg",
    sellValue: 5,
  },
  {
    id: 135,
    name: "Jolteon",
    rarity: "rare",
    image: "/135.jpg",
    sellValue: 5,
  },
  {
    id: 136,
    name: "Flareon",
    rarity: "rare",
    image: "/136.jpg",
    sellValue: 5,
  },
  {
    id: 137,
    name: "Porygon",
    rarity: "common",
    image: "/137.jpg",
    sellValue: 1,
  },
  {
    id: 138,
    name: "Omanyte",
    rarity: "uncommon",
    image: "/138.jpg",
    sellValue: 2,
  },
  {
    id: 139,
    name: "Omastar",
    rarity: "rare",
    image: "/139.jpg",
    sellValue: 5,
  },
  {
    id: 140,
    name: "Kabuto",
    rarity: "uncommon",
    image: "/137.jpg",
    sellValue: 2,
  },
  {
    id: 141,
    name: "Kabutops",
    rarity: "rare",
    image: "/141.jpg",
    sellValue: 5,
  },
  {
    id: 142,
    name: "Aerodactyl",
    rarity: "rare",
    image: "/142.jpg",
    sellValue: 5,
  },
  {
    id: 143,
    name: "Snorlax",
    rarity: "uncommon",
    image: "/143.jpg",
    sellValue: 2,
  },
  {
    id: 144,
    name: "Articuno",
    rarity: "rare",
    image: "/144.jpg",
    sellValue: 5,
  },
  {
    id: 145,
    name: "Zapdos EX",
    rarity: "doubleRare",
    image: "/145.jpg",
    sellValue: 10,
  },
  {
    id: 146,
    name: "Moltres",
    rarity: "rare",
    image: "/146.jpg",
    sellValue: 5,
  },
  {
    id: 147,
    name: "Dratini",
    rarity: "common",
    image: "/147.jpg",
    sellValue: 1,
  },
  {
    id: 148,
    name: "Dragonair",
    rarity: "uncommon",
    image: "/148.jpg",
    sellValue: 2,
  },
  {
    id: 149,
    name: "Dragonite",
    rarity: "rare",
    image: "/149.jpg",
    sellValue: 5,
  },
  {
    id: 150,
    name: "Mewtwo",
    rarity: "rare",
    image: "/150.jpg",
    sellValue: 5,
  },
  {
    id: 151,
    name: "Mew",
    rarity: "doubleRare",
    image: "/151.jpg",
    sellValue: 10,
  },
  {
    id: 152,
    name: "Energy Sticker",
    rarity: "uncommon",
    image: "/152.jpg",
    sellValue: 2,
  },
  {
    id: 153,
    name: "Snatch Arm",
    rarity: "uncommon",
    image: "/153.jpg",
    sellValue: 2,
  },
  {
    id: 154,
    name: "Old Helix Fossil",
    rarity: "uncommon",
    image: "/154.jpg",
    sellValue: 2,
  },
  {
    id: 155,
    name: "Old Dome Fossil",
    rarity: "uncommon",
    image: "/155.jpg",
    sellValue: 2,
  },
  {
    id: 156,
    name: "Old Amber",
    rarity: "uncommon",
    image: "/156.jpg",
    sellValue: 2,
  },
  {
    id: 157,
    name: "Safety Goggles",
    rarity: "uncommon",
    image: "/157.jpg",
    sellValue: 2,
  },
  {
    id: 158,
    name: "Big Balloon",
    rarity: "uncommon",
    image: "/158.jpg",
    sellValue: 2,
  },
  {
    id: 159,
    name: "Extra Tight Belt",
    rarity: "uncommon",
    image: "/159.jpg",
    sellValue: 2,
  },
  {
    id: 160,
    name: "Leftovers",
    rarity: "uncommon",
    image: "/160.jpg",
    sellValue: 2,
  },
  {
    id: 161,
    name: "Erika's Invitation",
    rarity: "uncommon",
    image: "/161.jpg",
    sellValue: 2,
  },
  {
    id: 162,
    name: "Giovanni's Charisma",
    rarity: "uncommon",
    image: "/162.jpg",
    sellValue: 2,
  },
  {
    id: 163,
    name: "Daisy's Assistance",
    rarity: "uncommon",
    image: "/163.jpg",
    sellValue: 2,
  },
  {
    id: 164,
    name: "Bill's Transfer",
    rarity: "uncommon",
    image: "/164.jpg",
    sellValue: 2,
  },
  {
    id: 165,
    name: "Cycling Road",
    rarity: "uncommon",
    image: "/165.jpg",
    sellValue: 2,
  },
  {
    id: 166,
    name: "Bulbasaur",
    rarity: "artRare",
    image: "/166.jpg",
    sellValue: 100,
  },
  {
    id: 167,
    name: "Ivysaur",
    rarity: "artRare",
    image: "/167.jpg",
    sellValue: 100,
  },
  {
    id: 168,
    name: "Charmander",
    rarity: "artRare",
    image: "/168.jpg",
    sellValue: 100,
  },
  {
    id: 169,
    name: "Charmeleon",
    rarity: "artRare",
    image: "/169.jpg",
    sellValue: 100,
  },
  {
    id: 170,
    name: "Squirtle",
    rarity: "artRare",
    image: "/170.jpg",
    sellValue: 100,
  },
  {
    id: 171,
    name: "Wartortle",
    rarity: "artRare",
    image: "/171.jpg",
    sellValue: 100,
  },
  {
    id: 172,
    name: "Caterpie",
    rarity: "artRare",
    image: "/172.jpg",
    sellValue: 100,
  },
  {
    id: 173,
    name: "Pikachu",
    rarity: "artRare",
    image: "/173.jpg",
    sellValue: 150,
  },
  {
    id: 174,
    name: "Nidoking",
    rarity: "artRare",
    image: "/174.jpg",
    sellValue: 100,
  },
  {
    id: 175,
    name: "Psyduck",
    rarity: "artRare",
    image: "/175.jpg",
    sellValue: 100,
  },
  {
    id: 176,
    name: "Poliwhirl",
    rarity: "artRare",
    image: "/176.jpg",
    sellValue: 100,
  },
  {
    id: 177,
    name: "Machoke",
    rarity: "artRare",
    image: "/177.jpg",
    sellValue: 100,
  },
  {
    id: 178,
    name: "Tangela",
    rarity: "artRare",
    image: "/178.jpg",
    sellValue: 100,
  },
  {
    id: 179,
    name: "Mr. Mime",
    rarity: "artRare",
    image: "/179.jpg",
    sellValue: 100,
  },
  {
    id: 180,
    name: "Omanyte",
    rarity: "artRare",
    image: "/180.jpg",
    sellValue: 100,
  },
  {
    id: 181,
    name: "Snorlax",
    rarity: "artRare",
    image: "/181.jpg",
    sellValue: 100,
  },
  {
    id: 182,
    name: "Dragonair",
    rarity: "artRare",
    image: "/182.jpg",
    sellValue: 100,
  },
  {
    id: 183,
    name: "Mewtwo",
    rarity: "artRare",
    image: "/183.jpg",
    sellValue: 100,
  },
  {
    id: 184,
    name: "Venusaur EX",
    rarity: "superRare",
    image: "/184.jpg",
    sellValue: 200,
  },
  {
    id: 185,
    name: "Charizard EX",
    rarity: "superRare",
    image: "/185.jpg",
    sellValue: 300,
  },
  {
    id: 186,
    name: "Blastoise EX",
    rarity: "superRare",
    image: "/186.jpg",
    sellValue: 200,
  },
  {
    id: 187,
    name: "Arbok EX",
    rarity: "superRare",
    image: "/187.jpg",
    sellValue: 200,
  },
  {
    id: 188,
    name: "Ninetails EX",
    rarity: "superRare",
    image: "/188.jpg",
    sellValue: 200,
  },
  {
    id: 189,
    name: "Wigglytuff EX",
    rarity: "superRare",
    image: "/189.jpg",
    sellValue: 200,
  },
  {
    id: 190,
    name: "Alakazam EX",
    rarity: "superRare",
    image: "/190.jpg",
    sellValue: 200,
  },
  {
    id: 191,
    name: "Golem EX",
    rarity: "superRare",
    image: "/184.jpg",
    sellValue: 200,
  },
  {
    id: 192,
    name: "Kangaskhan EX",
    rarity: "superRare",
    image: "/192.jpg",
    sellValue: 200,
  },
  {
    id: 193,
    name: "Jynx EX",
    rarity: "superRare",
    image: "/193.jpg",
    sellValue: 200,
  },
  {
    id: 194,
    name: "Zapdos EX",
    rarity: "superRare",
    image: "/194.jpg",
    sellValue: 200,
  },
  {
    id: 195,
    name: "Mew EX",
    rarity: "superRare",
    image: "/195.jpg",
    sellValue: 200,
  },
  {
    id: 196,
    name: "Erika's Invitation",
    rarity: "superRare",
    image: "/196.jpg",
    sellValue: 1500,
  },
  {
    id: 197,
    name: "Giovanni's Charisma",
    rarity: "superRare",
    image: "/197.jpg",
    sellValue: 300,
  },
  {
    id: 198,
    name: "Daisy's Assistance",
    rarity: "superRare",
    image: "/198.jpg",
    sellValue: 300,
  },
  {
    id: 199,
    name: "Bill's Transfer",
    rarity: "superRare",
    image: "/199.jpg",
    sellValue: 300,
  },
  {
    id: 200,
    name: "Venusaur EX",
    rarity: "secretArtRare",
    image: "/200.jpg",
    sellValue: 500,
  },
  {
    id: 201,
    name: "Charizard EX",
    rarity: "secretArtRare",
    image: "/201.jpg",
    sellValue: 2000,
  },
  {
    id: 202,
    name: "Blastoise EX",
    rarity: "secretArtRare",
    image: "/202.jpg",
    sellValue: 500,
  },
  {
    id: 203,
    name: "Alakazam EX",
    rarity: "secretArtRare",
    image: "/203.jpg",
    sellValue: 1000,
  },
  {
    id: 204,
    name: "Zapdos EX",
    rarity: "secretArtRare",
    image: "/204.jpg",
    sellValue: 1000,
  },
  {
    id: 205,
    name: "Mew EX",
    rarity: "secretArtRare",
    image: "/205.jpg",
    sellValue: 2000,
  },
  {
    id: 206,
    name: "Erika's Invitation",
    rarity: "secretArtRare",
    image: "/206.jpg",
    sellValue: 3000,
  },
  {
    id: 207,
    name: "Giovanni's Charisma",
    rarity: "secretArtRare",
    image: "/207.jpg",
    sellValue: 1000,
  },
  {
    id: 208,
    name: "Mew EX",
    rarity: "ultraRare",
    image: "/208.jpg",
    sellValue: 500,
  },
  {
    id: 209,
    name: "Switch",
    rarity: "ultraRare",
    image: "/209.jpg",
    sellValue: 500,
  },
  {
    id: 210,
    name: "Psychic Energy",
    rarity: "ultraRare",
    image: "/210.jpg",
    sellValue: 500,
  },
];
